Initialize StringBuilder to suitable size
typelevel/scalacheck pull request #778
Opened 2021-04-03 10:18 UTC by martijnhoekstra

2021-04-03 14:29 UTC, larsrh approved these changes

2021-04-03 23:46 UTC, ashawley requested changes

2021-04-03 23:46 UTC, ashawley commented on src/main/scala/org/scalacheck/Gen.scala
> +      mkString(n, new StringBuilder(n), gc, p, seed)
The behavior of `Gen.stringOfN` may allow negatives atm.  Might a negative ''n'' throw an exception?

2021-04-05 13:29 UTC, larsrh commented
Thanks @martijnhoekstra!

2021-04-05 13:29 UTC, merged